"""Export FableForge-14B model in quantized formats (GGUF, AWQ, GPTQ)."""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


@dataclass
class QuantizeConfig:
    """Configuration for model quantization and export."""

    model_path: str = "output/merged"
    output_dir: str = "output/quantized"
    formats: list[str] = field(default_factory=lambda: ["gguf", "awq", "gptq"])
    # GGUF settings
    gguf_quantization: str = "Q4_K_M"
    gguf_context_length: int = 8192
    # AWQ settings
    awq_bits: int = 4
    awq_group_size: int = 128
    awq_zero_point: bool = True
    # GPTQ settings
    gptq_bits: int = 4
    gptq_group_size: int = 128
    gptq_desc_act: bool = False
    # Calibration settings
    calibration_dataset: str = "allenai/dolma"
    calibration_samples: int = 128
    calibration_seq_length: int = 2048


def export_gguf(config: QuantizeConfig) -> dict[str, Any]:
    """Export model in GGUF format for llama.cpp.

    Args:
        config: QuantizeConfig with GGUF settings.

    Returns:
        Dictionary with export results.
    """
    logger.info(f"Exporting GGUF format ({config.gguf_quantization})")

    output_path = Path(config.output_dir) / f"gguf-{config.gguf_quantization.lower()}"
    output_path.mkdir(parents=True, exist_ok=True)

    convert_script = f"""#!/bin/bash
# Convert to GGUF format — Generated by FableForge-14B
set -e

MODEL_PATH="{config.model_path}"
OUTPUT_DIR="{output_path}"
QUANT="{config.gguf_quantization}"

# Step 1: Convert to GGUF F16
python -m llama_cpp.convert_hf_to_gguf \\
    $MODEL_PATH \\
    --outfile $OUTPUT_DIR/f16.gguf \\
    --outtype f16

# Step 2: Quantize
llama-quantize \\
    $OUTPUT_DIR/f16.gguf \\
    $OUTPUT_DIR/model-$QUANT.gguf \\
    $QUANT

echo "GGUF export complete: $OUTPUT_DIR/model-$QUANT.gguf"
"""

    script_path = output_path / "convert_gguf.sh"
    with open(script_path, "w") as f:
        f.write(convert_script)

    return {
        "format": "gguf",
        "quantization": config.gguf_quantization,
        "output_path": str(output_path),
        "script": str(script_path),
    }


def export_awq(config: QuantizeConfig) -> dict[str, Any]:
    """Export model in AWQ format.

    Args:
        config: QuantizeConfig with AWQ settings.

    Returns:
        Dictionary with export results.
    """
    logger.info(f"Exporting AWQ format (bits={config.awq_bits}, group_size={config.awq_group_size})")

    output_path = Path(config.output_dir) / "awq"
    output_path.mkdir(parents=True, exist_ok=True)

    quantize_script = f'''"""AWQ quantization — Generated by FableForge-14B"""

from transformers import AutoModelForCausalLM, AutoTokenizer, AutoConfig
from awq import AutoAWQForCausalLM
import torch

model_path = "{config.model_path}"
output_dir = "{output_path}"

# Load model
model = AutoAWQForCausalLM.from_pretrained(
    model_path,
    safetensors=True,
    device_map="auto",
)
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)

# Quantize
quant_config = {{
    "zero_point": {config.awq_zero_point},
    "q_group_size": {config.awq_group_size},
    "w_bit": {config.awq_bits},
    "version": "GEMM",
}}

model.quantize(tokenizer, quant_config=quant_config)

# Save
model.save_quantized(output_dir)
tokenizer.save_pretrained(output_dir)

print(f"AWQ model saved to {{output_dir}}")
'''

    script_path = output_path / "quantize_awq.py"
    with open(script_path, "w") as f:
        f.write(quantize_script)

    return {
        "format": "awq",
        "bits": config.awq_bits,
        "group_size": config.awq_group_size,
        "output_path": str(output_path),
        "script": str(script_path),
    }


def export_gptq(config: QuantizeConfig) -> dict[str, Any]:
    """Export model in GPTQ format.

    Args:
        config: QuantizeConfig with GPTQ settings.

    Returns:
        Dictionary with export results.
    """
    logger.info(f"Exporting GPTQ format (bits={config.gptq_bits}, group_size={config.gptq_group_size})")

    output_path = Path(config.output_dir) / "gptq"
    output_path.mkdir(parents=True, exist_ok=True)

    quantize_script = f'''"""GPTQ quantization — Generated by FableForge-14B"""

from transformers import AutoModelForCausalLM, AutoTokenizer, GPTQConfig
import torch

model_path = "{config.model_path}"
output_dir = "{output_path}"

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)

# Configure GPTQ quantization
gptq_config = GPTQConfig(
    bits={config.gptq_bits},
    group_size={config.gptq_group_size},
    desc_act={str(config.gptq_desc_act).lower()},
    dataset=["auto-gptq/quantize-data"],
    tokenizer=tokenizer,
)

# Load and quantize model
model = AutoModelForCausalLM.from_pretrained(
    model_path,
    quantization_config=gptq_config,
    torch_dtype=torch.float16,
    device_map="auto",
)

# Save
model.save_pretrained(output_dir)
tokenizer.save_pretrained(output_dir)

print(f"GPTQ model saved to {{output_dir}}")
'''

    script_path = output_path / "quantize_gptq.py"
    with open(script_path, "w") as f:
        f.write(quantize_script)

    return {
        "format": "gptq",
        "bits": config.gptq.bits,
        "group_size": config.gptq_group_size,
        "output_path": str(output_path),
        "script": str(script_path),
    }


def quantize(config: QuantizeConfig | None = None) -> dict[str, Any]:
    """Export the model in all configured quantized formats.

    Args:
        config: QuantizeConfig with all export settings.

    Returns:
        Dictionary with export results for each format.
    """
    if config is None:
        config = QuantizeConfig()

    logger.info("=" * 60)
    logger.info("Quantizing FableForge-14B")
    logger.info("=" * 60)
    logger.info(f"Model: {config.model_path}")
    logger.info(f"Formats: {config.formats}")

    results = {}

    if "gguf" in config.formats:
        results["gguf"] = export_gguf(config)

    if "awq" in config.formats:
        results["awq"] = export_awq(config)

    if "gptq" in config.formats:
        results["gptq"] = export_gptq(config)

    # Save overall config
    output_path = Path(config.output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    config_path = output_path / "quantize_config.json"
    with open(config_path, "w") as f:
        json.dump(config.__dict__, f, indent=2, default=str)

    logger.info(f"Quantization configs saved to {config_path}")

    return {
        "status": "configured",
        "formats": list(results.keys()),
        "results": results,
    }
